function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "INC_Counter"};
	this.sidHashMap["INC_Counter"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "INC_Counter:9"};
	this.sidHashMap["INC_Counter:9"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Num"] = {sid: "INC_Counter:1"};
	this.sidHashMap["INC_Counter:1"] = {rtwname: "<Root>/Num"};
	this.rtwnameHashMap["<Root>/Dashboard Scope"] = {sid: "INC_Counter:14"};
	this.sidHashMap["INC_Counter:14"] = {rtwname: "<Root>/Dashboard Scope"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "INC_Counter:23"};
	this.sidHashMap["INC_Counter:23"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "INC_Counter:9"};
	this.sidHashMap["INC_Counter:9"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "INC_Counter:4"};
	this.sidHashMap["INC_Counter:4"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<S1>/Input"] = {sid: "INC_Counter:10"};
	this.sidHashMap["INC_Counter:10"] = {rtwname: "<S1>/Input"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "INC_Counter:2"};
	this.sidHashMap["INC_Counter:2"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "INC_Counter:5"};
	this.sidHashMap["INC_Counter:5"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Constant1"] = {sid: "INC_Counter:24"};
	this.sidHashMap["INC_Counter:24"] = {rtwname: "<S1>/Constant1"};
	this.rtwnameHashMap["<S1>/From"] = {sid: "INC_Counter:16"};
	this.sidHashMap["INC_Counter:16"] = {rtwname: "<S1>/From"};
	this.rtwnameHashMap["<S1>/From2"] = {sid: "INC_Counter:20"};
	this.sidHashMap["INC_Counter:20"] = {rtwname: "<S1>/From2"};
	this.rtwnameHashMap["<S1>/From3"] = {sid: "INC_Counter:21"};
	this.sidHashMap["INC_Counter:21"] = {rtwname: "<S1>/From3"};
	this.rtwnameHashMap["<S1>/Goto"] = {sid: "INC_Counter:15"};
	this.sidHashMap["INC_Counter:15"] = {rtwname: "<S1>/Goto"};
	this.rtwnameHashMap["<S1>/Goto1"] = {sid: "INC_Counter:19"};
	this.sidHashMap["INC_Counter:19"] = {rtwname: "<S1>/Goto1"};
	this.rtwnameHashMap["<S1>/Relational Operator"] = {sid: "INC_Counter:8"};
	this.sidHashMap["INC_Counter:8"] = {rtwname: "<S1>/Relational Operator"};
	this.rtwnameHashMap["<S1>/Switch"] = {sid: "INC_Counter:7"};
	this.sidHashMap["INC_Counter:7"] = {rtwname: "<S1>/Switch"};
	this.rtwnameHashMap["<S1>/Unit Delay"] = {sid: "INC_Counter:3"};
	this.sidHashMap["INC_Counter:3"] = {rtwname: "<S1>/Unit Delay"};
	this.rtwnameHashMap["<S1>/Output"] = {sid: "INC_Counter:11"};
	this.sidHashMap["INC_Counter:11"] = {rtwname: "<S1>/Output"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
