function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "AverageCalculator"};
	this.sidHashMap["AverageCalculator"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "AverageCalculator:16"};
	this.sidHashMap["AverageCalculator:16"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Array"] = {sid: "AverageCalculator:2"};
	this.sidHashMap["AverageCalculator:2"] = {rtwname: "<Root>/Array"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "AverageCalculator:16"};
	this.sidHashMap["AverageCalculator:16"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Sum"] = {sid: "AverageCalculator:13"};
	this.sidHashMap["AverageCalculator:13"] = {rtwname: "<Root>/Sum"};
	this.rtwnameHashMap["<Root>/Min"] = {sid: "AverageCalculator:14"};
	this.sidHashMap["AverageCalculator:14"] = {rtwname: "<Root>/Min"};
	this.rtwnameHashMap["<Root>/Max"] = {sid: "AverageCalculator:15"};
	this.sidHashMap["AverageCalculator:15"] = {rtwname: "<Root>/Max"};
	this.rtwnameHashMap["<S1>/Array"] = {sid: "AverageCalculator:17"};
	this.sidHashMap["AverageCalculator:17"] = {rtwname: "<S1>/Array"};
	this.rtwnameHashMap["<S1>/From"] = {sid: "AverageCalculator:3"};
	this.sidHashMap["AverageCalculator:3"] = {rtwname: "<S1>/From"};
	this.rtwnameHashMap["<S1>/From1"] = {sid: "AverageCalculator:11"};
	this.sidHashMap["AverageCalculator:11"] = {rtwname: "<S1>/From1"};
	this.rtwnameHashMap["<S1>/From2"] = {sid: "AverageCalculator:12"};
	this.sidHashMap["AverageCalculator:12"] = {rtwname: "<S1>/From2"};
	this.rtwnameHashMap["<S1>/Goto"] = {sid: "AverageCalculator:4"};
	this.sidHashMap["AverageCalculator:4"] = {rtwname: "<S1>/Goto"};
	this.rtwnameHashMap["<S1>/MinMax"] = {sid: "AverageCalculator:9"};
	this.sidHashMap["AverageCalculator:9"] = {rtwname: "<S1>/MinMax"};
	this.rtwnameHashMap["<S1>/MinMax1"] = {sid: "AverageCalculator:10"};
	this.sidHashMap["AverageCalculator:10"] = {rtwname: "<S1>/MinMax1"};
	this.rtwnameHashMap["<S1>/Sum of Elements"] = {sid: "AverageCalculator:1"};
	this.sidHashMap["AverageCalculator:1"] = {rtwname: "<S1>/Sum of Elements"};
	this.rtwnameHashMap["<S1>/Sum"] = {sid: "AverageCalculator:18"};
	this.sidHashMap["AverageCalculator:18"] = {rtwname: "<S1>/Sum"};
	this.rtwnameHashMap["<S1>/Min"] = {sid: "AverageCalculator:19"};
	this.sidHashMap["AverageCalculator:19"] = {rtwname: "<S1>/Min"};
	this.rtwnameHashMap["<S1>/Max"] = {sid: "AverageCalculator:20"};
	this.sidHashMap["AverageCalculator:20"] = {rtwname: "<S1>/Max"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
