function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Counter"};
	this.sidHashMap["Counter"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Counter:2"};
	this.sidHashMap["Counter:2"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "Counter:2"};
	this.sidHashMap["Counter:2"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Dashboard Scope"] = {sid: "Counter:5"};
	this.sidHashMap["Counter:5"] = {rtwname: "<Root>/Dashboard Scope"};
	this.rtwnameHashMap["<Root>/Dashboard Scope1"] = {sid: "Counter:6"};
	this.sidHashMap["Counter:6"] = {rtwname: "<Root>/Dashboard Scope1"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "Counter:7"};
	this.sidHashMap["Counter:7"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Scope1"] = {sid: "Counter:9"};
	this.sidHashMap["Counter:9"] = {rtwname: "<Root>/Scope1"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "Counter:3"};
	this.sidHashMap["Counter:3"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "Counter:4"};
	this.sidHashMap["Counter:4"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<S1>:44"] = {sid: "Counter:2:44"};
	this.sidHashMap["Counter:2:44"] = {rtwname: "<S1>:44"};
	this.rtwnameHashMap["<S1>:46"] = {sid: "Counter:2:46"};
	this.sidHashMap["Counter:2:46"] = {rtwname: "<S1>:46"};
	this.rtwnameHashMap["<S1>:45"] = {sid: "Counter:2:45"};
	this.sidHashMap["Counter:2:45"] = {rtwname: "<S1>:45"};
	this.rtwnameHashMap["<S1>:48"] = {sid: "Counter:2:48"};
	this.sidHashMap["Counter:2:48"] = {rtwname: "<S1>:48"};
	this.rtwnameHashMap["<S1>:47"] = {sid: "Counter:2:47"};
	this.sidHashMap["Counter:2:47"] = {rtwname: "<S1>:47"};
	this.rtwnameHashMap["<S1>:50"] = {sid: "Counter:2:50"};
	this.sidHashMap["Counter:2:50"] = {rtwname: "<S1>:50"};
	this.rtwnameHashMap["<S1>:44:2"] = {sid: "Counter:2:44:2"};
	this.sidHashMap["Counter:2:44:2"] = {rtwname: "<S1>:44:2"};
	this.rtwnameHashMap["<S1>:44:3"] = {sid: "Counter:2:44:3"};
	this.sidHashMap["Counter:2:44:3"] = {rtwname: "<S1>:44:3"};
	this.rtwnameHashMap["<S1>:46:2"] = {sid: "Counter:2:46:2"};
	this.sidHashMap["Counter:2:46:2"] = {rtwname: "<S1>:46:2"};
	this.rtwnameHashMap["<S1>:46:3"] = {sid: "Counter:2:46:3"};
	this.sidHashMap["Counter:2:46:3"] = {rtwname: "<S1>:46:3"};
	this.rtwnameHashMap["<S1>:48:1"] = {sid: "Counter:2:48:1"};
	this.sidHashMap["Counter:2:48:1"] = {rtwname: "<S1>:48:1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
